cms(using cbvs)/blog/urls.py
from django.urls import path
from blog.views import Home, Detail, Update, Delete, Create, Index
# , Create, )

app_name = 'blog'
urlpatterns = [
    path('create/', Create.as_view(), name='create'),
    path('blog/', Index.as_view(), name='all'),
    path('', Home.as_view(), name='home'),
    path('<int:pk>', Detail.as_view(), name='detail'),
    path('<int:pk>/edit/', Update.as_view(), name='edit'),
    path('<int:pk>/delete/', Delete.as_view(), name='delete')
]

cms(using cbvs)/cms/urls.py
from django.contrib import admin
from django.urls import path, include
# from blog.views import home, post_page, all_posts, create_post, delete_post, edit_post

urlpatterns = [
    path('', include('blog.urls')),
    path('admin/', admin.site.urls)
    # path('', home),
    # path('post/<int:post_id>/', post_page),
    # path('allposts/', all_posts),
    # path('create/', create_post),
    # path('delete/<int:post_id>/', delete_post),
    # path('edit/<int:post_id>/', edit_post),
]

cms(using cbvs)/blog/models.py
from django.db import models

# Create your models here.


class Blog(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    objects = None

    def __str__(self):
        return self.title

    # objects = models.Blog()

cms(using cbvs)/blog/forms.py
from django.forms import ModelForm
from blog.models import Blog


# Create the form class.
class BlogForm(ModelForm):
    class Meta:
        model = Blog
        fields = ['title', 'content']

cms(using cbvs)/blog/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import ListView, CreateView, UpdateView, DetailView, DeleteView, View
from django.urls import reverse_lazy

from blog.models import Blog
from blog.forms import BlogForm
# Create your views here.


class Index(ListView):
    model = Blog


class Home(View):
    def get(self, request):
        return render(request, "blog/home.html")


class Detail(DetailView):
    model = Blog


class Create(CreateView):
    model = Blog
    fields = ['title', 'content']
    success_url = reverse_lazy('blog:all')


class Update(UpdateView):
    model = Blog
    # fields = ['title', 'content']
    template = 'blog/blog_update.html'
    success_url = reverse_lazy('blog:all')

    def get(self, request, pk):
        blog = get_object_or_404(self.model, pk=pk)
        # try:
        #     blog = request.POST.get(pk, 0)
        # except e:
        #     raise

        # print(blog.title)
        ctx = {'title': blog.title, 'content': blog.content}
        # print(ctx)
        return render(request, self.template, ctx)

    def post(self, request, pk):
        blog = get_object_or_404(self.model, pk=pk)
        form = BlogForm(request.POST, instance=blog)
        if not form.is_valid():
            ctx = {'title': blog.title, 'content': blog.content}
            return render(request, self.template, ctx)

        form.save()
        return redirect(self.success_url)


class Delete(DeleteView):
    model = Blog
    fields = ['title', 'content']
    success_url = reverse_lazy('blog:all')

    # model = Blog
    # success_url = reverse_lazy('blog:all')
    # template = 'blog/blog_confirm_delete.html'

    # def get(self, request, pk):
    #     blog = get_object_or_404(self.model, pk=pk)
    #     form = BlogForm(instance=blog)
    #     ctx = {'blog': blog}
    #     return render(request, self.template, ctx)

    # def post(self, request, pk):
    #     make = get_object_or_404(self.model, pk=pk)
    #     make.delete()
    #     return redirect(self.success_url)


# def home(request):
#     return render(request, 'home.html')


# def post_page(request, post_id):
#     # print(post_id)
#     post = Blog.objects.get(pk=post_id)
#     return render(request, "post.html", {"post": post})


# def all_posts(request):
#     all_posts = Blog.objects.all()
#     return render(request, "allposts.html", {"posts": all_posts})


# def create_post(request):
#     if request.method == "POST":
#         # print(request.POST)
#         title = request.POST["title"]
#         content = request.POST["content"]

#         new_post = Blog.objects.create(title=title, content=content)

#         return redirect("/allposts/")
#     return render(request, "create_post.html")


# def delete_post(request, post_id):
#     post = Blog.objects.get(pk=post_id)
#     post.delete()
#     return redirect("/allposts/")


# def edit_post(request, post_id):
#     post = Blog.objects.get(pk=post_id)
#     if request.method == "POST":
#         title = request.POST["title"]
#         content = request.POST["content"]

#         post.title = title
#         post.content = content

#         post.save()

#         return redirect(f'/post/{post.id}')
#     return render(request, "edit_post.html", {"post": post})

cms(using cbvs)/blog/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>TIDSOL</title>
    <link rel="stylesheet" href="https://bootswatch.com/4/darkly/bootstrap.min.css">
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container">

            <a class="navbar-brand" href="#">TIDSOL</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup"
                aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                <div class="navbar-nav ml-auto">
                    <a class="nav-link active" href="{% url 'blog:home' %} ">Home <span
                            class="sr-only">(current)</span></a>
                    <a class="nav-link" href="{% url 'blog:all' %} ">All Posts</a>
                    <a class="nav-link" href=" {% url 'blog:create' %} ">Create New Post</a>

                </div>
            </div>
        </div>
    </nav>
    <br><br>{% block body %} {%endblock%}
</body>

</html>

cms(using cbvs)/blog/templates/blog/blog_confirm_delete.html
{% extends "base.html" %}
{% block body %}
<div class="container">

    <h1>Delete Blog</h1>
    <p>Are you sure you want to delete the blog: {{blog}}?</p>

    <form action="" method="POST">
        {% csrf_token %}
        <input type="submit" value="Yes, delete.">
    </form>
</div>

{% endblock %}

cms(using cbvs)/blog/templates/blog/blog_detail.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
    <a href="{% url 'blog:home' %}">Back to Catalog</a>
    <h1>{{blog.title}}</h1>
    <a class="btn btn-md btn-primary" href="{% url 'blog:edit' blog.id %}">Edit</a>
    <a class="btn btn-md btn-danger" href="{% url 'blog:delete' blog.id %}">Delete</a>
    <p> Published on {{blog.created}} </p>
    <hr>
    <p> {{blog.content}} </p>
</div>
{% endblock %}

cms(using cbvs)/blog/templates/blog/blog_form.html
{% extends 'base.html' %}
{% block body %}
<br><br>
<div class="container">
    <h1>Create New Post</h1>
    <hr>
    <form  method="POST">
        {% csrf_token %}
        <p>Title</p>
        <input type="text" class="form-control" name="title">
        <br>
        <p>Content</p>
        <textarea class="form-control" name="content"> </textarea>
        <br>
        <button type="submit" class="btn btn-success">Create Post</button>
    </form>
</div>
{% endblock %}

cms(using cbvs)/blog/templates/blog/blog_list.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
    {% if blog_list %}
    {% for blog in blog_list %}
    <a href="{% url 'blog:detail' blog.id%}">
        <h1> {{blog.title}} </h1>
        <p> {{blog.content}} </p>
    </a>
    <hr> {%endfor%}
    {% else%}
    <p>There are no posts</p>
    {% endif %}
    <a class="btn btn-secondary" href=" {% url 'blog:create' %} ">Create New Post</a>

</div>
{% endblock %}

cms(using cbvs)/blog/templates/blog/blog_update.html
{% extends 'base.html' %}
{% block body %}
<br><br>
<div class="container">
    <h1>Edit Post</h1>
    <hr>
    <form method="POST">
        {% csrf_token %}
        <p>Title</p>
        <input type="text" class="form-control" name="title" value="{{title}}">
        <br>
        <p>Content</p>
        <textarea class="form-control" name="content">{{content}}</textarea>
        <br>
        <button type=" submit" class="btn btn-success">Save Post</button>
        <input type="submit" onclick="window.location='{% url 'blog:all' %}' ; return false;" value="Cancel">
    </form>
</div>
{% endblock %}

cms(using cbvs)/blog/templates/blog/home.html
{% extends 'base.html' %}
{% block body %}
<title>My Blog</title>
<link rel="stylesheet" href="/static/home.css">
<div class="container">
    <img class="header-img" src="/static/homescape.jpg" alt="pic of a laptop">
    <br><br>

    <h1>TIDSOL</h1>
    <p>Things I don't say out loud</p>
</div>
{% endblock %}